<a href="https://colab.research.google.com/github/mastgm0817/Python/blob/main/submission/mastgm0817/lecture/numpy_%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
array1 = np.array([2,3,4,5,6,7,7,8,9])
array2 = np.array([[1,2,3,4],[5,7,8,9],[1,2,3,4]])
print(array2)
print(array2.shape) # 3행 4열의 배열



[[1 2 3 4]
 [5 7 8 9]
 [1 2 3 4]]
(3, 4)


In [3]:
import numpy as np

array1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) # numpy 배열 생성

print(array1)

array1.shape # numpy 배열의 차원을 알려줌



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


(3, 4)

In [5]:
import numpy as np

array1 = np.arange(1,101)
print(array1)


[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


(100,)

In [6]:
import numpy as np

array1 = np.arange(3,101,3)
array1

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [13]:
import numpy as np
array1 = np.array([2,3,5,6,7,8,9,20,33])
array1[0]
array1[2]
array1[:-1] # 인덱스 마지막 원소를 제외하고 모두 출력
array1[[1,3,4]] #인덱스 번호에 해당하는 값이 출력됨
array1[0:7] #처음부터 인덱스 7번까지 출력
array1[:7] #결과는 위와 같음
array1[2:11:2] #2번 인덱스부터 시작하여 2개씩 건너뛰어 값 출력

array([ 5,  7,  9, 33])

In [21]:
import numpy as np
array1 = [0,1,2,3,4,5,6,7,8,9,10]
array2 = np.arange(0,11)
array3 = np.arange(0,11)

#numpy를 쓰는 이유? 연산의 간편함
# 예제 1. numpy를 사용하지 않고 배열의 연산

for i in range(len(array1)):
  array1[i] = 2 * array1[i]
print(array1)

# 예제 2. numpy를 사용해서 배열의 연산

array2 = 2 * array2
print(array2)


array3 * 2
array3 + 2
array1 + array3 # 주의! array 사이즈가 다르면 연산이 안된다.

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
[ 0  2  4  6  8 10 12 14 16 18 20]


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [28]:
import numpy as np

# numpy Boolean 연산법

array1 =  np.arange(1,11)
array1 > 4 # array1 원소중에 4보다 큰 값은 True로 

array1 % 2 == 0 # array1 원소중에 짝수인 애들만

booleans = np.array([True,True,False,True,False,False,True,True,False,False])

np.where(booleans)
np.where(array1>4) #array1에서 4보다 큰 값이 있는 인덱스만 불러옴

(array([4, 5, 6, 7, 8, 9]),)

In [42]:
numbers = [1,2,3,4,5]
number = map(lambda x: x**2, numbers)
print(type(number))

strings = ["1","2","3","4"]
string = map(int, strings) #리스트 자료형으로 반환해주기때문에 리스트형으로 형변환을 해줘야한다.
string = list(map(int, strings))
print(string) 

x, y = map(int, input("숫자를 입력하세요.").split())
sum = x + y
sum

# to be continued

<class 'map'>
[1, 2, 3, 4]
숫자를 입력하세요.5 10


15